name: Testando a regra de protect rule

on:
  branch_protection_rule:
    types: [created, edited, deleted]

jobs:
  print-modification:
    runs-on: ubuntu-latest
    steps:
    
      - name: Avisa sobre modificacoes
        run: echo "Este WKF foi triggado pois uma branch protect rule foi alterada"
